#Deployment do banco de dados
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postegre
spec:
  selector:
    matchLabels:
      app: postegre
  template:
    metadata:
      labels:
        app: postegre
    spec:
      containers:
      - name: postegre
        image: postegres:13.16
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: fakeshop
          - name: POSTGRES_USER
            value: fakeshop
          - name: POSTGRES_PASSWORD
            value: Pg1234
---
apiVersion: v1
kind: Service
metadata:
  name: postegre
spec:
  selector:
    app: postegre
  ports:
  - port: 5432
    targetPort: 5432
---
#Deployment da aplicação web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakeshop
spec:
  selector:
    matchLabels:
      app: fakeshop
  template:
    metadata:
      labels:
        app: fakeshop
    spec:
      containers:
      - name: fakeshop
        image: conafly/fake-shop:v1
        ports:
          - containerPort: 5000
        env:
          - name: DB_HOST
            value: postgre
          - name: DB_USER
            value: fakeshop
          - name: DB_PASSWROD
            value: Pg1234
          - name: DB_NAME
            value: fakeshop
          - name: FLASK_APP
            value: index.py
---
apiVersion: v1
kind: Service
metadata:
  name: fakeshop
spec:
  selector:
    app: fakeshop
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer